language: python
python:
  - "3.5"
install:
  pip install -r requirements.txt;
script:
  - flake8 .
  - coverage run manage.py test
after_success:
  - codecov
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com