language: python
python:
  - "3.9"
install:
  pip install -r dev-requirements.txt;
script:
  - flake8 .
  - coverage run manage.py test --settings=mprjlabeler.test_settings
after_success:
  - codecov
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com
