version: '2'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '127.0.0.1:35432:5432'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./redisdata:/data

  web:
    build: '.'
    image: 'websource'
    command: './app.sh'
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./media:/media
      - .:/app
    depends_on:
      - postgres
      - redis

  celery_worker:
    image: 'websource'
    command: './app.sh'
    environment:
      WORKER: 1 
    volumes_from:
      - web
    depends_on:
      - web
