# Generated by Django 4.1 on 2023-08-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessosColetados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consulta_data_etl", models.DateTimeField()),
                ("consulta_resposta_status", models.CharField(max_length=400)),
                ("processo_numero", models.CharField(max_length=20)),
                ("processo_json", models.JSONField()),
                ("etl_tag_1", models.TextField(blank=True, null=True)),
                ("etl_checksumid_1", models.TextField(unique=True)),
                ("etl_dt_check", models.DateTimeField()),
                ("etl_dt_criacao", models.DateTimeField()),
                ("etl_dt_ult_atualiz", models.DateTimeField()),
            ],
            options={
                "db_table": "processos_coletados",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessosDiasAColetar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateTimeField(blank=True, null=True)),
                ("data_final", models.DateTimeField(blank=True, null=True)),
                ("consulta_data_etl", models.DateTimeField(blank=True, null=True)),
                (
                    "consulta_resposta_status",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "consulta_resposta_texto",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("consulta_resposta_json", models.TextField(blank=True, null=True)),
                ("consulta_resposta_raw", models.BinaryField(blank=True, null=True)),
                ("etl_checksumid_1", models.TextField(unique=True)),
                ("etl_checksumid_2", models.TextField()),
                ("etl_dt_check", models.DateTimeField()),
                ("etl_dt_criacao", models.DateTimeField()),
                ("etl_dt_ult_atualiz", models.DateTimeField()),
            ],
            options={
                "db_table": "processos_dias_a_coletar",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReusProcessosColetados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_processos_coletados", models.IntegerField()),
                ("consulta_data_etl", models.DateTimeField()),
                ("processo_numero", models.CharField(max_length=20)),
                ("etl_tag_1", models.TextField(blank=True, null=True)),
                ("pessoa_reu", models.CharField(blank=True, max_length=400, null=True)),
                ("pessoa_tipo", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "pessoa_doc_tipo",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "pessoa_doc_codigo",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "pessoa_doc_emissor",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("etl_checksumid_1", models.TextField(unique=True)),
                ("etl_dt_check", models.DateTimeField()),
                ("etl_dt_criacao", models.DateTimeField()),
                ("etl_dt_ult_atualiz", models.DateTimeField()),
            ],
            options={
                "db_table": "reus_processos_coletados",
                "managed": False,
            },
        ),
    ]
