# Generated by Django 5.0.2 on 2024-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filtro", "0016_alter_filtro_reu"),
    ]

    operations = [
        migrations.AddField(
            model_name="filtro",
            name="status",
            field=models.CharField(
                choices=[("1", "Ativo"), ("2", "Inativo")], default="1", max_length=1
            ),
        ),
    ]
