# Generated by Django 5.0.2 on 2024-03-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filtro", "0017_filtro_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="filtro",
            name="arquivo_tabulado",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
